<?php
$GLOBALS['films'] = array(
  array(
    "Nom" => "Forrest Gump",
    "Année" => 1994,
    "Durée" => "2h20min",
    "Réalisateur" => "Robert Zemeckis",
    "Acteurs" => array("Tom Hanks", "Gary Siniseplus", "Brad Pitt"),
    "Genres" => array("Comédie dramatique" , "Romance"),
    "Like" => 100806,
    "Affiche" => "http://www.goldposter.com/wp-content/uploads/2015/04/Forrest-Gump_poster_goldposter_com_7.jpg",
    "Privé" => true
  ),
  array(
    "Nom" => "Django Unchained",
    "Année" => 2013,
    "Durée" => "2h44min",
    "Réalisateur" => "Quentin Tarantino",
    "Acteurs" => array("Jamie Foxx", "Christoph Waltz", "Clint Eastwood"),
    "Genres" => array("Western"),
    "Like" => 10030,
    "Affiche" => "http://www.filmosphere.com/wp-content/uploads/2012/12/Django-Unchained-affiche.jpg",
    "Privé" => true
  ),
  array(
    "Nom" => "La Ligne verte",
    "Année" => 2000,
    "Durée" => "3h9min",
    "Réalisateur" => "Frank Darabont",
    "Acteurs" => array("Tom Hanks", "Michael Clarke Duncan",  "Brad Pitt"),
    "Genres" => array("Fantastique" , "Policier"),
    "Like" => 20030,
    "Privé" => false,
    "Affiche" => "http://www.notrecinema.com/images/cache/la-ligne-verte-poster_50432_40929.jpg",
  ),
  array(
    "Nom" => "Gran Torino",
    "Année" => 2009,
    "Durée" => "1h51min",
    "Réalisateur" => "Clint Eastwood",
    "Acteurs" => array("Clint Eastwood", "Bee Vangplus"),
    "Genres" => array("Drame" , "Thriller"),
    "Like" => 1030,
    "Privé" => false,
    "Affiche" => "http://images.moviepostershop.com/gran-torino-movie-poster-2008-1020420150.jpg",
  ),
  array(
    "Nom" => "La Liste de Schindler",
    "Année" => 1994,
    "Durée" => "3h15min",
    "Réalisateur" => "Steven Spielberg",
    "Acteurs" => array("Liam Neeson", "Ben Kingsleyplus", "Christian Bale"),
    "Genres" => array("Historique", "Drame"),
    "Like" => 60070,
    "Privé" => false,
    "Affiche" => "http://www.avoir-alire.com/IMG/arton4582.jpg?1414452369",
  ),
  array(
    "Nom" => "The Dark Knight, Le Chevalier Noir",
    "Année" => 2008,
    "Durée" => "2h27min",
    "Réalisateur" => "Christopher Nolan",
    "Acteurs" => array("Christian Bale", "Heath Ledger"),
    "Genres" => array("Action" , "Drame"),
    "Like" => 89030,
    "Privé" => false,
    "Affiche" => "http://fr.web.img2.acsta.net/medias/nmedia/18/63/97/89/18949761.jpg",
  ),
  array(
    "Nom" => "Le Parrain",
    "Année" => 1972,
    "Durée" => "2h55min",
    "Réalisateur" => "Francis Ford Coppola",
    "Acteurs" => array("Marlon Brando", "Al Pacino"),
    "Genres" => array("Policier" , "Drame"),
    "Like" => 60180,
    "Privé" => true,
    "Affiche" => "http://fr.web.img4.acsta.net/medias/nmedia/18/35/57/73/18660716.jpg",
  ),
  array(
    "Nom" => "Pulp Fiction",
    "Année" => 1994,
    "Durée" => "2h29min",
    "Réalisateur" => "Quentin Tarantino",
    "Acteurs" => array("John Travolta", "Samuel L. Jackson", "Jamie Foxx"),
    "Genres" => array("Policier" , "Thriller"),
    "Like" => 40078,
    "Privé" => false,
    "Affiche" => "http://www.movpins.com/big/MV5BMTU2Mjc0MTg4MF5BMl5BanBnXkFtZTcwOTA0MzU5Ng/pulp-fiction-(1994)-large-picture.jpg",
  ),
  array(
    "Nom" => "Le Seigneur des anneaux",
    "Année" => 2003,
    "Durée" => "3h20min",
    "Réalisateur" => "Peter Jackson",
    "Acteurs" => array("Elijah Wood", "Sean Astin", "Brad Pitt"),
    "Genres" => array("Fantastique" , "Aventure"),
    "Like" => 80050,
    "Privé" => false,
    "Affiche" => "http://papystreaming.com/fr/files/2013/09/Le-Seigneur-des-anneaux-Le-Retour-du-roi.jpg",
  ),
  array(
    "Nom" => "Fight Club",
    "Année" => 1999,
    "Durée" => "2h15min",
    "Réalisateur" => "David Fincher",
    "Acteurs" => array("Brad Pitt", "Edward Norton", "Liam Neeson"),
    "Genres" => array("Thriller" , "Drame"),
    "Like" => 8010,
    "Privé" => false,
    "Affiche" => "https://ok2disconnectportfolio.files.wordpress.com/2012/02/fight-club-hi-res-poster-vertical-a31.jpg",
  ),
  array(
    "Nom" => "Intouchables",
    "Année" => 2011,
    "Durée" => "1h52min",
    "Réalisateur" => "Eric Toledano",
    "Acteurs" => array("François Cluzet", "Omar Sy", "Jamie Foxx"),
    "Genres" => array("Comédie"),
    "Like" => 89010,
    "Privé" => true,
    "Affiche" => "http://ourfaithinaction.net/wp-content/uploads/2012/07/the-intouchables-movie-poster1.jpg",
  ),
  array(
    "Nom" => "Mommy",
    "Année" => 2014,
    "Durée" => "2h18min",
    "Réalisateur" => "Xavier Dolan",
    "Acteurs" => array("Viviane Pascal", "Antoine-Olivier", "Brad Pitt"),
    "Genres" => array("Drame"),
    "Like" => 59070,
    "Privé" => false,
    "Affiche" => "https://41.media.tumblr.com/64a0d6d20e5e419b4b894aef542a7abb/tumblr_nm5m3etarH1szjhaso1_500.png",
  )
